const craft_keywords = {
  en: [
    "attempt",
    "augment",
    "change",
    "corrupt",
    "enchant",
    "fracture",
    "improves",
    "randomise",
    "reforge",
    "remove",
    "reroll",
    "sacrifice",
    "set",
    "split",
    "synthesise",
    "upgrade",
  ],
  ru: [
    "Попытаться",
    "Усилить",
    "Заменить |Обменять стопку|Обменять уникальный", // This is the current issue
    "Осквернить",
    "Зачаровать",
    "Расколоть",
    "Повысить",
    "Случайным образом",
    "Перековать",
    "Убрать",
    "Изменить значения",
    "Пожертвовать |Потратить ",
    "Добавить новое",
    "split",
    "Синтезировать",
    "Улучшить",
  ],
};

export default craft_keywords;
