import { get } from "svelte/store";
import { crafts, settings } from "../stores";
import { formatPrice } from "./formatPrice";

let leagues = {
  std: "Standard",
  lsc: "Sentinel Softcore",
  lhc: "Sentinel Hardcore",
};

export const formatPost = () => {
  const currentCrafts = get(crafts);
  const currentSettings = get(settings);
  let length = 0;
  let post = ``;

  // Add league.
  post += `**WTS ${leagues[currentSettings.league]}**`;

  // Add IGN.
  if (currentSettings.username && currentSettings.username.trim() !== "") {
    post += ` - IGN: **${currentSettings.username}**`;
  }

  // Add generated by.
  post += ` \`| generated by HarvestMonster\``;

  // Add a newline.
  post += `\n`;

  // Add custom notes.

  // Determine max craft name length to calculate buffer later.
  currentCrafts.forEach((craft) => {
    if (craft.name.length > length) length = craft.name.length;
  });

  // Add crafts.
  for (let craft of currentCrafts) {
    const bufferLength = length - craft.name.length + 4;
    const buffer = Array.from(Array(bufferLength), () => "").join(" ");
    post += `   \`${craft.quantity}x ${craft.name}${buffer} [${
      craft.level > 0 ? craft.level : "83"
    }]  <${formatPrice(craft.price)}>\`\n`;
  }

  return post;
};
